# Generated by Django 4.0.1 on 2022-01-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("item_description", models.CharField(max_length=10000)),
                ("item_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("item_quantity", models.IntegerField(default=0)),
                (
                    "collection",
                    models.ManyToManyField(
                        blank=True,
                        related_name="inventory_items",
                        to="crud_app.InventoryCollection",
                    ),
                ),
            ],
        ),
    ]
